<p dir = 'rtl'>  درس دوم.بخش دوم (series) </p>

In [1]:
import pandas as pd

In [2]:
s1 = pd.Series([1, 3, 5, None, 9, 11, 13])

In [3]:
s1.count()

6

In [4]:
s1.sum()

42.0

In [5]:
s1.product()

19305.0

In [6]:
s1.prod()

19305.0

In [7]:
s1.sum(skipna=True)

42.0

In [8]:
s1.sum(skipna=False)

nan

In [9]:
s1.cumsum()

0     1.0
1     4.0
2     9.0
3     NaN
4    18.0
5    29.0
6    42.0
dtype: float64

In [10]:
s1

0     1.0
1     3.0
2     5.0
3     NaN
4     9.0
5    11.0
6    13.0
dtype: float64

In [11]:
s1.cumsum(skipna=False)

0    1.0
1    4.0
2    9.0
3    NaN
4    NaN
5    NaN
6    NaN
dtype: float64

In [12]:
s1.pct_change()

C:\Users\Mahi\AppData\Local\Temp\ipykernel_15244\3382261067.py:1: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  s1.pct_change()


0         NaN
1    2.000000
2    0.666667
3    0.000000
4    0.800000
5    0.222222
6    0.181818
dtype: float64

In [13]:
s1

0     1.0
1     3.0
2     5.0
3     NaN
4     9.0
5    11.0
6    13.0
dtype: float64

In [14]:
s1.pct_change(fill_method='ffill')

C:\Users\Mahi\AppData\Local\Temp\ipykernel_15244\2350275203.py:1: FutureWarning: The 'fill_method' keyword being not None and the 'limit' keyword in Series.pct_change are deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  s1.pct_change(fill_method='ffill')


0         NaN
1    2.000000
2    0.666667
3    0.000000
4    0.800000
5    0.222222
6    0.181818
dtype: float64

In [15]:
s1.pct_change(fill_method='pad')

C:\Users\Mahi\AppData\Local\Temp\ipykernel_15244\2155512861.py:1: FutureWarning: The 'fill_method' keyword being not None and the 'limit' keyword in Series.pct_change are deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  s1.pct_change(fill_method='pad')


0         NaN
1    2.000000
2    0.666667
3    0.000000
4    0.800000
5    0.222222
6    0.181818
dtype: float64

In [16]:
s1.pct_change(fill_method='backfill')

C:\Users\Mahi\AppData\Local\Temp\ipykernel_15244\615886237.py:1: FutureWarning: The 'fill_method' keyword being not None and the 'limit' keyword in Series.pct_change are deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  s1.pct_change(fill_method='backfill')


0         NaN
1    2.000000
2    0.666667
3    0.800000
4    0.000000
5    0.222222
6    0.181818
dtype: float64

In [17]:
s1.pct_change(fill_method='ffill')

C:\Users\Mahi\AppData\Local\Temp\ipykernel_15244\2350275203.py:1: FutureWarning: The 'fill_method' keyword being not None and the 'limit' keyword in Series.pct_change are deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  s1.pct_change(fill_method='ffill')


0         NaN
1    2.000000
2    0.666667
3    0.000000
4    0.800000
5    0.222222
6    0.181818
dtype: float64

In [18]:
s1.min()

1.0

In [19]:
s1.max()

13.0

In [20]:
min(s1), max(s1)

(1.0, 13.0)

In [21]:
sum(s1)

nan

In [22]:
s1.mean()

7.0

In [23]:
s1

0     1.0
1     3.0
2     5.0
3     NaN
4     9.0
5    11.0
6    13.0
dtype: float64

In [24]:
s1.median()

7.0

In [25]:
s1.mode()

0     1.0
1     3.0
2     5.0
3     9.0
4    11.0
5    13.0
dtype: float64

In [26]:
s1.std()

4.732863826479693

In [27]:
s1.var()

22.4

In [28]:
s1.var()**0.5

4.732863826479693

In [29]:
s1.describe()

count     6.000000
mean      7.000000
std       4.732864
min       1.000000
25%       3.500000
50%       7.000000
75%      10.500000
max      13.000000
dtype: float64

In [30]:
s1.sample()

1    3.0
dtype: float64

In [31]:
for _ in range(10):
    print(s1.sample())

4    9.0
dtype: float64
0    1.0
dtype: float64
6    13.0
dtype: float64
0    1.0
dtype: float64
6    13.0
dtype: float64
5    11.0
dtype: float64
2    5.0
dtype: float64
1    3.0
dtype: float64
4    9.0
dtype: float64
1    3.0
dtype: float64


In [32]:
s1

0     1.0
1     3.0
2     5.0
3     NaN
4     9.0
5    11.0
6    13.0
dtype: float64

In [33]:
s1.sample(5)

3     NaN
5    11.0
4     9.0
6    13.0
0     1.0
dtype: float64

In [34]:
s1.sample(n=15, replace=True)

1     3.0
0     1.0
6    13.0
1     3.0
5    11.0
1     3.0
0     1.0
0     1.0
2     5.0
0     1.0
6    13.0
2     5.0
3     NaN
1     3.0
2     5.0
dtype: float64

In [35]:
s1.unique()

array([ 1.,  3.,  5., nan,  9., 11., 13.])

In [36]:
s2 = pd.Series([1, 3, 7, 2, 1, 3, 8, 4, 1, 3, 4, 8])

In [37]:
s2.unique()

array([1, 3, 7, 2, 8, 4], dtype=int64)

In [38]:
s2.nunique()

6

In [39]:
s2.count()

12

In [40]:
s2.mode()

0    1
1    3
dtype: int64

In [41]:
s3 = pd.Series([1, 3, 5, 7, 9, 11, 13, 15, 17, 19])

In [42]:
s4 = pd.Series([2, 4, 6, 8, 10, 12])

In [43]:
s3 + 5

0     6
1     8
2    10
3    12
4    14
5    16
6    18
7    20
8    22
9    24
dtype: int64

In [44]:
2*s3 - 4

0    -2
1     2
2     6
3    10
4    14
5    18
6    22
7    26
8    30
9    34
dtype: int64

In [45]:
s3 + s4

0     3.0
1     7.0
2    11.0
3    15.0
4    19.0
5    23.0
6     NaN
7     NaN
8     NaN
9     NaN
dtype: float64

In [46]:
s3.count()

10

In [47]:
s4.count()

6

In [48]:
s3 - s4

0   -1.0
1   -1.0
2   -1.0
3   -1.0
4   -1.0
5   -1.0
6    NaN
7    NaN
8    NaN
9    NaN
dtype: float64

In [49]:
5/2

2.5

In [50]:
5//2

2

In [51]:
s3//2

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [52]:
s3.add(5)

0     6
1     8
2    10
3    12
4    14
5    16
6    18
7    20
8    22
9    24
dtype: int64

In [53]:
s3 + 5

0     6
1     8
2    10
3    12
4    14
5    16
6    18
7    20
8    22
9    24
dtype: int64

In [54]:
s3/3

0    0.333333
1    1.000000
2    1.666667
3    2.333333
4    3.000000
5    3.666667
6    4.333333
7    5.000000
8    5.666667
9    6.333333
dtype: float64

In [55]:
(s3/3).round()

0    0.0
1    1.0
2    2.0
3    2.0
4    3.0
5    4.0
6    4.0
7    5.0
8    6.0
9    6.0
dtype: float64

In [56]:
s3/s4

0    0.500000
1    0.750000
2    0.833333
3    0.875000
4    0.900000
5    0.916667
6         NaN
7         NaN
8         NaN
9         NaN
dtype: float64

In [57]:
s5 = pd.Series([1,3,5,7,9])

In [58]:
list(s5)

[1, 3, 5, 7, 9]

In [59]:
dict(s5)

{0: 1, 1: 3, 2: 5, 3: 7, 4: 9}

In [60]:
s5.values

array([1, 3, 5, 7, 9], dtype=int64)

In [61]:
import numpy as np

In [62]:
np.array(s5)

array([1, 3, 5, 7, 9], dtype=int64)

In [63]:
tuple(s5)

(1, 3, 5, 7, 9)

In [64]:
s6 = pd.Series(
    data=[1,2,3,4,5,6], 
    index=['A','B','C','D','E','F'])

In [65]:
dict(s6)

{'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5, 'F': 6}

In [66]:
list(s6)

[1, 2, 3, 4, 5, 6]

In [67]:
np.array(s6)

array([1, 2, 3, 4, 5, 6], dtype=int64)

In [68]:
2 in s5

True

In [69]:
2 in s5.index

True

In [70]:
2 in s5.values

False

In [71]:
0 in s5

True

In [72]:
s6

A    1
B    2
C    3
D    4
E    5
F    6
dtype: int64

In [73]:
'A' in s6

True

In [74]:
0 in s6

False